name = "dyeli-forms-backend"
main = "./index.js"
compatibility_date = "2022-10-18"
# Don't want is accessible directly via URL, only via service binding.
workers_dev = false

kv_namespaces = [
  # Session KV
  { binding = "SESSION_STORE", id = "", preview_id = "" }
]

[vars]
  SAMPLES_TABLE = "Samples Orders"
  WEB_FEEDB_TABLE = "Website Feedback"
  ONLINE_FEEDB_TABLE = "Online Order Feedback"
  STORE_FEEDB_TABLE = "In-store Feedback"

[dev]
  port = 8971
